# Generated by Django 4.0.3 on 2022-03-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='URL'),
        ),
    ]
